resources:
- name: src-repo
  type: git
  source:
    branch: working
    private_key: ((git-repo.ssh_key))
    uri: ((git-repo.mirror1_uri))/SRMIC/bkd-quarkus.git
  check_every: 5m
- name: docker
  type: docker-image
  source:
    repository: ((docker-registry.repo))/bkd-quarkus
    username: ((docker-registry.username))
    password: ((docker-registry.password))

jobs:
- name: build-native-docker
  public: true
  serial_groups:
  plan:
  - aggregate:
    - get: src-repo
      trigger: true
  - task: build-native-jar
    file: src-repo/ci/build-native-jar.yml
  - put: docker
    params:
      build: .
      dockerfile: src-repo/src/main/docker/Dockerfile.concourse
      tag_as_latest: false